[tcpout]
defaultGroup = default-autolb-group

# ================================
# NAT NETWORK
# ================================
[tcpout:default-autolb-group]
server = 10.0.2.1:9997
[tcpout-server: 10.0.2.1:9997]

# ================================
# HOST-ONLY ADAPTER
# ================================
# [tcpout:default-autolb-group]
# server = 192.168.56.1:9997
# [tcpout-server: 192.168.56.1:9997]